// Code generated by MockGen. DO NOT EDIT.
// Source: analytics.go
//
// Generated by this command:
//
//	mockgen -source=analytics.go -destination=../mocks/analytics_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "lizzyCalc/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIOperationAnalytics is a mock of IOperationAnalytics interface.
type MockIOperationAnalytics struct {
	ctrl     *gomock.Controller
	recorder *MockIOperationAnalyticsMockRecorder
	isgomock struct{}
}

// MockIOperationAnalyticsMockRecorder is the mock recorder for MockIOperationAnalytics.
type MockIOperationAnalyticsMockRecorder struct {
	mock *MockIOperationAnalytics
}

// NewMockIOperationAnalytics creates a new mock instance.
func NewMockIOperationAnalytics(ctrl *gomock.Controller) *MockIOperationAnalytics {
	mock := &MockIOperationAnalytics{ctrl: ctrl}
	mock.recorder = &MockIOperationAnalyticsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOperationAnalytics) EXPECT() *MockIOperationAnalyticsMockRecorder {
	return m.recorder
}

// WriteOperation mocks base method.
func (m *MockIOperationAnalytics) WriteOperation(ctx context.Context, op domain.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteOperation", ctx, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteOperation indicates an expected call of WriteOperation.
func (mr *MockIOperationAnalyticsMockRecorder) WriteOperation(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteOperation", reflect.TypeOf((*MockIOperationAnalytics)(nil).WriteOperation), ctx, op)
}
