// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../mocks/repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "lizzyCalc/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIOperationRepository is a mock of IOperationRepository interface.
type MockIOperationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIOperationRepositoryMockRecorder
	isgomock struct{}
}

// MockIOperationRepositoryMockRecorder is the mock recorder for MockIOperationRepository.
type MockIOperationRepositoryMockRecorder struct {
	mock *MockIOperationRepository
}

// NewMockIOperationRepository creates a new mock instance.
func NewMockIOperationRepository(ctrl *gomock.Controller) *MockIOperationRepository {
	mock := &MockIOperationRepository{ctrl: ctrl}
	mock.recorder = &MockIOperationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOperationRepository) EXPECT() *MockIOperationRepositoryMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockIOperationRepository) GetHistory(ctx context.Context) ([]domain.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx)
	ret0, _ := ret[0].([]domain.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockIOperationRepositoryMockRecorder) GetHistory(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockIOperationRepository)(nil).GetHistory), ctx)
}

// Ping mocks base method.
func (m *MockIOperationRepository) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockIOperationRepositoryMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockIOperationRepository)(nil).Ping), ctx)
}

// SaveOperation mocks base method.
func (m *MockIOperationRepository) SaveOperation(ctx context.Context, op domain.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOperation", ctx, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOperation indicates an expected call of SaveOperation.
func (mr *MockIOperationRepositoryMockRecorder) SaveOperation(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOperation", reflect.TypeOf((*MockIOperationRepository)(nil).SaveOperation), ctx, op)
}
