// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=../mocks/usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "lizzyCalc/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockICalculatorUseCase is a mock of ICalculatorUseCase interface.
type MockICalculatorUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockICalculatorUseCaseMockRecorder
	isgomock struct{}
}

// MockICalculatorUseCaseMockRecorder is the mock recorder for MockICalculatorUseCase.
type MockICalculatorUseCaseMockRecorder struct {
	mock *MockICalculatorUseCase
}

// NewMockICalculatorUseCase creates a new mock instance.
func NewMockICalculatorUseCase(ctrl *gomock.Controller) *MockICalculatorUseCase {
	mock := &MockICalculatorUseCase{ctrl: ctrl}
	mock.recorder = &MockICalculatorUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICalculatorUseCase) EXPECT() *MockICalculatorUseCaseMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockICalculatorUseCase) Calculate(ctx context.Context, number1, number2 float64, operation string) (*domain.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", ctx, number1, number2, operation)
	ret0, _ := ret[0].(*domain.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockICalculatorUseCaseMockRecorder) Calculate(ctx, number1, number2, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockICalculatorUseCase)(nil).Calculate), ctx, number1, number2, operation)
}

// HandleOperationEvent mocks base method.
func (m *MockICalculatorUseCase) HandleOperationEvent(ctx context.Context, op domain.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleOperationEvent", ctx, op)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleOperationEvent indicates an expected call of HandleOperationEvent.
func (mr *MockICalculatorUseCaseMockRecorder) HandleOperationEvent(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleOperationEvent", reflect.TypeOf((*MockICalculatorUseCase)(nil).HandleOperationEvent), ctx, op)
}

// History mocks base method.
func (m *MockICalculatorUseCase) History(ctx context.Context) ([]domain.Operation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "History", ctx)
	ret0, _ := ret[0].([]domain.Operation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockICalculatorUseCaseMockRecorder) History(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockICalculatorUseCase)(nil).History), ctx)
}
